'use client';

import { useEffect, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';

interface BrandedQRCodeProps {
  value: string;
  size?: number;
  /** Override the logo image src. Defaults to the SweatDrop app icon. */
  logoSrc?: string;
  /** Logo size as a fraction of the QR code size (0–1). Default: 0.22 */
  logoFraction?: number;
  /** Corner radius of the logo, as a fraction of the logo size (0–0.5). Default: 0.22 (iOS-style squircle look). */
  logoCornerRadius?: number;
}

// ---------------------------------------------------------------------------
// Module-level rounded-logo cache
//
// Why this exists:
// Early implementations generated the rounded app icon inside each component's
// `useEffect`. That worked for one QR but broke in the Print Studio batch flow
// — when 20 `BrandedQRCode` instances mount at once and `window.print()` is
// called immediately after, Chrome captures the DOM before the per-instance
// canvas work has completed. The embedded `imageSettings.src` is still the
// fallback external URL, which the print pipeline then fails to render,
// leaving an empty square where the logo should be.
//
// The fix: rasterize the rounded icon exactly once per (src, radius) pair and
// memoize the data URL. The first mounted component warms the cache; all
// subsequent instances (including the N portal-mounted stickers in batch
// print) get the data URL synchronously on first render.
// ---------------------------------------------------------------------------

const roundedLogoCache = new Map<string, string>();
const roundedLogoPromises = new Map<string, Promise<string | null>>();

function cacheKey(src: string, radius: number): string {
  return `${src}::${radius}`;
}

async function generateRoundedLogo(src: string, radius: number): Promise<string | null> {
  try {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.decoding = 'async';
    img.src = src;
    await img.decode().catch(
      () =>
        new Promise<void>((resolve, reject) => {
          img.onload = () => resolve();
          img.onerror = () => reject(new Error('logo load failed'));
        }),
    );

    // Fixed high-resolution output — independent of the on-screen display size.
    // A 7" sticker at 300 dpi reaches ~2100 device pixels; the logo covers ~22%
    // (~460 device pixels). 512 gives comfortable headroom on both retina
    // screens and high-dpi print output.
    const px = 512;
    const canvas = document.createElement('canvas');
    canvas.width = px;
    canvas.height = px;
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';

    const r = Math.max(0, Math.min(0.5, radius)) * px;

    // White backdrop so the rounded corners don't expose QR modules behind.
    ctx.fillStyle = '#FFFFFF';
    roundedRectPath(ctx, 0, 0, px, px, r);
    ctx.fill();

    ctx.save();
    roundedRectPath(ctx, 0, 0, px, px, r);
    ctx.clip();
    ctx.drawImage(img, 0, 0, px, px);
    ctx.restore();

    return canvas.toDataURL('image/png');
  } catch {
    return null;
  }
}

function getRoundedLogo(src: string, radius: number): string | Promise<string | null> {
  const key = cacheKey(src, radius);
  const cached = roundedLogoCache.get(key);
  if (cached) return cached;

  const inflight = roundedLogoPromises.get(key);
  if (inflight) return inflight;

  const promise = generateRoundedLogo(src, radius).then((result) => {
    if (result) roundedLogoCache.set(key, result);
    roundedLogoPromises.delete(key);
    return result;
  });
  roundedLogoPromises.set(key, promise);
  return promise;
}

/**
 * Ensures the rounded-logo data URL is generated and cached. Call this before
 * `window.print()` in batch flows so every `BrandedQRCode` instance that
 * mounts inside a print portal renders with the embedded icon on the very
 * first paint (no empty excavation in the printed output).
 */
export async function warmLogoCache(
  src: string = '/app-icon.png',
  radius: number = 0.22,
): Promise<void> {
  const result = getRoundedLogo(src, radius);
  if (typeof result === 'string') return;
  await result;
}

/**
 * QR code with the SweatDrop app icon embedded in the center.
 * Uses error correction level H so the logo doesn't break scannability.
 *
 * The logo is rasterized once per (src, radius) pair into a shared module-level
 * cache so 20+ instances (batch sticker print) all render with the correct
 * embedded image on first paint — the print pipeline never captures an empty
 * placeholder.
 */
export function BrandedQRCode({
  value,
  size = 200,
  logoSrc = '/app-icon.png',
  logoFraction = 0.22,
  logoCornerRadius = 0.22,
}: BrandedQRCodeProps) {
  const logoSize = Math.round(size * logoFraction);

  // Synchronous cache read — if the rounded logo was generated by any earlier
  // instance, we get the data URL on the very first render.
  const initial = getRoundedLogo(logoSrc, logoCornerRadius);
  const [roundedSrc, setRoundedSrc] = useState<string | null>(
    typeof initial === 'string' ? initial : null,
  );

  useEffect(() => {
    // Cache miss — await the in-flight (or fresh) generation.
    if (roundedSrc) return;
    let cancelled = false;
    Promise.resolve(getRoundedLogo(logoSrc, logoCornerRadius)).then((result) => {
      if (cancelled) return;
      if (result) setRoundedSrc(result);
    });
    return () => {
      cancelled = true;
    };
  }, [logoSrc, logoCornerRadius, roundedSrc]);

  return (
    <QRCodeSVG
      value={value}
      size={size}
      level="H"
      includeMargin
      bgColor="#FFFFFF"
      fgColor="#000000"
      imageSettings={{
        src: roundedSrc ?? logoSrc,
        width: logoSize,
        height: logoSize,
        excavate: true,
      }}
    />
  );
}

function roundedRectPath(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
) {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.lineTo(x + w - radius, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + radius);
  ctx.lineTo(x + w, y + h - radius);
  ctx.quadraticCurveTo(x + w, y + h, x + w - radius, y + h);
  ctx.lineTo(x + radius, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - radius);
  ctx.lineTo(x, y + radius);
  ctx.quadraticCurveTo(x, y, x + radius, y);
  ctx.closePath();
}
