// Edge Function: distribute-leaderboard-prizes
// Description: Distributes leaderboard prizes at the end of weekly/monthly periods.
// Runs BEFORE the reset cron jobs to capture the final standings.
//
// AGENT NOTE: [2026-04-13] - edge-function-agent (Phase 2 — leaderboard_rewards_full_flow)
// Reference: /Users/np/.cursor/plans/leaderboard_rewards_full_flow_e0f01bd3.plan.md — Phase 2
//
// CHANGES vs previous version:
//   - Fetch the newly-created redemption rows after the RPC call (to get
//     redemption_id and redemption_code generated by the Phase-1 DB migration).
//   - Push notification body now includes a "collect at desk" CTA and the
//     4-character code so the user knows they need to act.
//   - Push data payload adds `redemption_id` for the mobile deep-link to the
//     specific redemption card, and `redemption_code` for display in notification.
//
// SCHEDULE:
//   Weekly: Sunday 22:55 UTC (5 min before weekly_drops reset at 23:00)
//   Monthly: Last day of month 22:55 UTC
//
// INTERFACE CONTRACT:
//   Input:  { period: "weekly" | "monthly" }
//   Output: { gyms_processed: number, total_winners: number, details: [...] }
//
// DEDUPE STRATEGY:
//   The RPC distribute_leaderboard_prizes itself guards against double-distribution
//   via the `prizes_distributed` flag on leaderboard_snapshots. The edge function
//   does NOT need an additional dedupe layer — if the RPC returns 0 winners, no
//   push is sent.
//
// FAILURE HANDLING:
//   - Per-gym errors are logged and skipped; remaining gyms continue.
//   - Per-user push failures are logged but do not abort the gym loop.
//   - Missing redemption rows (e.g. DB migration not yet applied) fall back to
//     the legacy push body gracefully — no crash.

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import {
  deliveryCountFromSendPushBody,
  compactSendPushMetrics,
} from '../_shared/expo-push.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
};

/** Rank suffix helper: 1→1st, 2→2nd, 3→3rd */
function ordinal(n: number): string {
  if (n === 1) return '1st';
  if (n === 2) return '2nd';
  if (n === 3) return '3rd';
  return `${n}th`;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    const supabase = createClient(supabaseUrl, serviceRoleKey, {
      auth: { persistSession: false },
    });

    // Determine period from request body or default to 'weekly'
    let period: string;
    try {
      const body = await req.json();
      period = body.period || 'weekly';
    } catch {
      period = 'weekly';
    }

    if (!['weekly', 'monthly'].includes(period)) {
      return new Response(
        JSON.stringify({ error: `Invalid period: ${period}` }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 400,
        }
      );
    }

    // Get all active gyms
    const { data: gyms, error: gymsError } = await supabase
      .from('gyms')
      .select('id, name')
      .eq('is_active', true);

    if (gymsError) throw gymsError;

    const details: Array<{
      gym_id: string;
      gym_name: string;
      winners: number;
      push_delivered?: number;
      push_metrics?: Record<string, unknown>[];
    }> = [];
    let totalWinners = 0;

    for (const gym of gyms || []) {
      // Check if gym has configured rewards for this period
      const { data: rewards } = await supabase
        .from('leaderboard_rewards')
        .select('id')
        .eq('gym_id', gym.id)
        .eq('period', period)
        .eq('is_active', true)
        .limit(1);

      if (!rewards || rewards.length === 0) continue;

      // Call distribute_leaderboard_prizes RPC
      const { data: winnersCount, error: distError } = await supabase.rpc(
        'distribute_leaderboard_prizes',
        { p_gym_id: gym.id, p_period: period }
      );

      if (distError) {
        console.error(JSON.stringify({
          event: 'distribute_leaderboard_rpc_error',
          gym_id: gym.id,
          message: distError.message,
        }));
        continue;
      }

      const winners = winnersCount || 0;
      totalWinners += winners;
      let pushDeliveredForGym = 0;
      const pushMetrics: Record<string, unknown>[] = [];

      if (winners > 0) {
        // Fetch the redemption rows just created for this gym/period so we
        // can include redemption_id and redemption_code in the push payload.
        // We filter by source_type='leaderboard_prize' and status='pending'
        // (Phase-1 migration) or 'claimed' (legacy) created within the last 5 minutes.
        const { data: newRedemptions } = await supabase
          .from('redemptions')
          .select('id, user_id, redemption_code, description')
          .eq('gym_id', gym.id)
          .eq('source_type', 'leaderboard_prize')
          .in('status', ['pending', 'claimed'])
          .gte('created_at', new Date(Date.now() - 5 * 60 * 1000).toISOString())
          .order('created_at', { ascending: false });

        // Build a map user_id → redemption for O(1) lookup
        const redemptionByUser = new Map<
          string,
          { id: string; code: string | null }
        >();
        for (const r of newRedemptions || []) {
          if (!redemptionByUser.has(r.user_id)) {
            redemptionByUser.set(r.user_id, {
              id: r.id,
              code: r.redemption_code ?? null,
            });
          }
        }

        // Get top 3 with leaderboard positions
        const { data: topUsers } = await supabase.rpc('get_leaderboard', {
          p_type: 'gym',
          p_scope_id: gym.id,
          p_period: period,
          p_limit: 3,
          p_newcomer_only: false,
        });

        if (topUsers) {
          for (const user of topUsers) {
            const { data: profile } = await supabase
              .from('profiles')
              .select('expo_push_token')
              .eq('id', user.user_id)
              .single();

            if (!profile?.expo_push_token) continue;

            const redemption = redemptionByUser.get(user.user_id);
            const hasCode = redemption?.code != null;

            // Push body: include collect CTA if redemption code exists (Phase-1 migration applied)
            const pushBody = hasCode
              ? `You finished ${ordinal(user.rank)} at ${gym.name} this ${period}! Show code ${redemption!.code} at the desk to collect your prize. 🎁`
              : `Congratulations! You finished ${ordinal(user.rank)} on the ${period} leaderboard at ${gym.name}! 🏆`;

            // Push data: include redemption_id for deep-link navigation
            const pushData: Record<string, string> = {
              type: 'leaderboard_prize',
              gym_id: gym.id,
              rank: String(user.rank),
              period,
            };
            if (redemption?.id) {
              pushData.redemption_id = redemption.id;
            }
            if (redemption?.code) {
              pushData.redemption_code = redemption.code;
            }

            const pushRes = await fetch(`${supabaseUrl}/functions/v1/send-push`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: `Bearer ${serviceRoleKey}`,
              },
              body: JSON.stringify({
                client_ref: 'leaderboard_prize',
                tokens: [profile.expo_push_token],
                title: '🏆 You Won a Leaderboard Prize!',
                body: pushBody,
                data: pushData,
              }),
            });

            const pushJson = await pushRes.json().catch(() => null);
            const delivered = deliveryCountFromSendPushBody(pushJson);
            pushDeliveredForGym += delivered;
            pushMetrics.push({
              user_id_prefix: String(user.user_id).slice(0, 8),
              rank: user.rank,
              has_redemption: !!redemption?.id,
              has_code: hasCode,
              ...compactSendPushMetrics(pushJson),
            });

            if (!pushRes.ok) {
              console.error(JSON.stringify({
                event: 'leaderboard_prize_push_http_error',
                gym_id: gym.id,
                rank: user.rank,
                http_status: pushRes.status,
              }));
            }
          }
        }
      }

      details.push({
        gym_id: gym.id,
        gym_name: gym.name,
        winners,
        push_delivered: winners > 0 ? pushDeliveredForGym : undefined,
        push_metrics: winners > 0 ? pushMetrics : undefined,
      });
    }

    console.log(JSON.stringify({
      event: 'distribute-leaderboard-prizes',
      period,
      gyms_processed: details.length,
      total_winners: totalWinners,
    }));

    return new Response(
      JSON.stringify({
        gyms_processed: details.length,
        total_winners: totalWinners,
        period,
        details,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error(JSON.stringify({
      event: 'distribute-leaderboard-prizes-fatal',
      message,
    }));

    return new Response(
      JSON.stringify({ error: message }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});
