export function PrivacyContentEn() {
  return (
    <div className="max-w-[760px] mx-auto px-4 sm:px-6 py-12 sm:py-16 pb-24">
      <h1 className="text-3xl sm:text-4xl font-display font-bold text-text mb-2 tracking-tight">
        Privacy Policy
      </h1>
      <p className="text-sm text-text-3 mb-12">Last updated: March 17, 2026.</p>

      <div className="bg-primary/5 border border-primary/20 rounded-xl p-5 sm:p-6 mb-10">
        <p className="text-text-2 leading-relaxed m-0">
          SweatDrop is a gym gamification platform. This policy explains what data we collect, why we collect it and how we use it. Please read it in full — especially the section on health data.
        </p>
      </div>

      <section className="legal-content space-y-6">
        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">1. Who we are</h2>
        <p className="text-text-2 leading-relaxed">
          SweatDrop (&quot;we&quot;, &quot;us&quot;, &quot;SweatDrop&quot;) is a software platform that provides gamification services to gyms and their members. For the purposes of applicable data protection law (including the Law on Personal Data Protection of the Republic of Serbia), the data controller is:
        </p>
        <p className="text-text-2 leading-relaxed">
          <strong className="text-text">SweatDrop</strong><br />
          Belgrade, Serbia<br />
          Email: <a href="mailto:support@sweat-drop.com" className="text-primary hover:underline">support@sweat-drop.com</a>
        </p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">2. What data we collect</h2>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">2.1 Data you provide</h3>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li><strong className="text-text">Account:</strong> Name, email address and authentication credentials. Passwords are stored using one-way hashing and are not stored in readable form.</li>
          <li><strong className="text-text">Sign-in providers:</strong> If you use Google or Apple sign-in, we receive identity data from that provider as allowed by your settings (for example name, email and provider user ID). For email sign-in, we may require email verification before full app access.</li>
          <li><strong className="text-text">Profile:</strong> Username, profile photo, gym name</li>
          <li><strong className="text-text">Health and physical data (optional):</strong> Gender, body weight, height, date of birth, training goal. You provide these voluntarily during profile setup and use them for personalised recommendations. You can skip or delete them at any time.</li>
        </ul>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">2.2 Data generated by using the app</h3>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li><strong className="text-text">Workout sessions:</strong> Date, time, duration, drops earned, average RPM, calories</li>
          <li><strong className="text-text">Check-in data:</strong> Date and time of check-in, gym, GPS distance from gym (number only, not precise location)</li>
          <li><strong className="text-text">GPS location:</strong> We collect your location <em>only</em> when you scan the reception QR code, to confirm you are physically at the gym. We do not track location continuously.</li>
          <li><strong className="text-text">Bluetooth (BLE) data:</strong> RPM and metrics from equipment sensors. Data is processed on device and only aggregated results are sent.</li>
          <li><strong className="text-text">Gamification:</strong> Drops balance, badges, leaderboard rank, challenge progress, reward history</li>
          <li><strong className="text-text">Social features:</strong> Referral invites, friend challenge records, and related progress needed to run invite-friend and 1v1 challenge features.</li>
          <li><strong className="text-text">Push notifications:</strong> Device push token, delivery status and notification preferences needed to send account, activity and campaign notifications.</li>
        </ul>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">2.3 Technical data</h3>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li>Device type, operating system, app version</li>
          <li>IP address (for security and abuse prevention)</li>
          <li>Error and performance logs</li>
        </ul>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">3. Why we collect data (legal basis)</h2>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">3.1 Contract performance</h3>
        <p className="text-text-2 leading-relaxed">To provide core services — account creation, session tracking, drops calculation, leaderboard display and reward management in the Store.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">3.2 Legitimate interest</h3>
        <p className="text-text-2 leading-relaxed">To prevent check-in fraud (GPS verification), platform security, and improving service quality based on aggregated usage data.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">3.3 Consent</h3>
        <p className="text-text-2 leading-relaxed">For health data (body weight, height, date of birth, training goal). You give consent voluntarily during profile setup and can withdraw it at any time by deleting that data from your profile.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">3.4 Legal obligation</h3>
        <p className="text-text-2 leading-relaxed">Retention of data to the extent required by applicable law.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">4. Who sees your data</h2>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">4.1 Gym owner</h3>
        <p className="text-text-2 leading-relaxed">The owner of the gym where you are active can see:</p>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li>Your name, avatar and activity only at <em>their</em> gym</li>
          <li>Number of sessions, drops earned at their gym, date of last visit</li>
          <li>Your fitness goal (e.g. &quot;fitness&quot;) — not body weight, height or date of birth</li>
          <li>Your rank on their gym&apos;s leaderboard</li>
        </ul>
        <p className="text-text-2 leading-relaxed">The gym owner <strong className="text-text">cannot see</strong> your activity at other gyms, your email, body weight, height or date of birth.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">4.2 Other app users</h3>
        <p className="text-text-2 leading-relaxed">On the public leaderboard, your username, avatar, drops count and rank are visible. You can turn off your public profile in settings.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">4.3 SweatDrop team</h3>
        <p className="text-text-2 leading-relaxed">Our team has access to data only to provide support, resolve technical issues and prevent abuse.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">4.4 Third parties</h3>
        <p className="text-text-2 leading-relaxed">We do not sell your data. We use the following trusted service providers:</p>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li><strong className="text-text">Supabase</strong> — database and authentication, servers in the EU</li>
          <li><strong className="text-text">Expo / EAS</strong> — mobile app distribution</li>
          <li><strong className="text-text">Sentry</strong> (if enabled) — anonymous error reporting</li>
        </ul>
        <p className="text-text-2 leading-relaxed">We use service providers that process personal data on our instructions and apply appropriate contractual safeguards under applicable law.</p>
        <h3 className="text-base font-semibold text-text-2 mt-7 mb-2">4.5 Sweat Arenas — cross-gym visibility</h3>
        <p className="text-text-2 leading-relaxed">By joining a Sweat Arena you accept that your score and username are visible to all arena participants, including members of other participating gyms.</p>
        <p className="text-text-2 leading-relaxed">Visible: username, avatar, total arena score. Not visible: which gym your points come from, body weight, height, email or any other personal data.</p>
        <p className="text-text-2 leading-relaxed">The arena sponsor sees only aggregated data (number of participants, total activity) — never individual user data.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">5. GPS location — details</h2>
        <p className="text-text-2 leading-relaxed">We use GPS location <strong className="text-text">only</strong> when you scan the reception QR code, to confirm you are within 200 metres of the gym. We do not store precise coordinates — only the calculated distance in metres and whether verification succeeded.</p>
        <p className="text-text-2 leading-relaxed">If you deny location access, check-in still works — we only record that GPS verification was not possible. We do <strong className="text-text">not</strong> track your location continuously.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">6. How long we keep data</h2>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li><strong className="text-text">Account and profile:</strong> While the account is active. After deletion — 30-day retention period, then permanent deletion.</li>
          <li><strong className="text-text">Workout sessions and check-ins:</strong> 3 years from last activity</li>
          <li><strong className="text-text">Health data:</strong> Until you delete it or delete your account</li>
          <li><strong className="text-text">Logs:</strong> 90 days</li>
        </ul>
        <p className="text-text-2 leading-relaxed">Some data may be retained for longer where required by law or needed for security, fraud prevention or dispute resolution, for the minimum period necessary.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">7. Your rights</h2>
        <p className="text-text-2 leading-relaxed">Under applicable data protection law you have the right to:</p>
        <ul className="list-disc pl-6 text-text-2 space-y-2">
          <li><strong className="text-text">Access</strong> the data we hold about you</li>
          <li><strong className="text-text">Correct</strong> inaccurate data (in the app or by email)</li>
          <li><strong className="text-text">Delete</strong> your account and all data — via Settings → Delete account</li>
          <li><strong className="text-text">Port</strong> your data (export in JSON format — contact us)</li>
          <li><strong className="text-text">Object</strong> to processing based on legitimate interest</li>
          <li><strong className="text-text">Withdraw consent</strong> for health data at any time</li>
        </ul>
        <p className="text-text-2 leading-relaxed">For any request, email us at <a href="mailto:support@sweat-drop.com" className="text-primary hover:underline">support@sweat-drop.com</a>. We respond within 30 days.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">8. Data security</h2>
        <p className="text-text-2 leading-relaxed">All data is transmitted encrypted (TLS 1.3). Passwords are never stored in readable form — we use bcrypt hashing. The database is on Supabase infrastructure in the EU with automatic backups and encryption at rest.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">9. Children</h2>
        <p className="text-text-2 leading-relaxed">SweatDrop is not intended for anyone under 13. We require a minimum age of 13 at registration. If we learn we have collected data from a child under 13, we delete the account immediately.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">10. Changes to this policy</h2>
        <p className="text-text-2 leading-relaxed">We will notify you of significant changes by email or in-app notification at least 14 days before they take effect. The last updated date is always shown at the top of this page.</p>

        <h2 className="text-xl font-semibold text-text mt-12 mb-4 pb-2 border-b border-border">11. Contact</h2>
        <p className="text-text-2 leading-relaxed">For any privacy questions:<br /><a href="mailto:support@sweat-drop.com" className="text-primary hover:underline">support@sweat-drop.com</a></p>
      </section>
    </div>
  );
}
