-- Migration: 20260423000001_create_global_achievement_badges_bucket.sql
-- Description: Creates the 'global-achievement-badges' public storage bucket for programmatically
--              generated badge PNGs (one per achievement code, 512×512 PNG-24).
--
-- IMPACT ON FRONTEND:
-- - Mobile App: Trophy Room reads badge_image_url from global_achievements — URLs resolve once
--               Phase 2 uploads the PNGs via `pnpm badges:upload`
-- - Admin Panel: Achievement list shows badge previews via <img> tags
--
-- BREAKING CHANGES: None
--
-- NEXT STEPS:
-- 1. cd backend && supabase db push
-- 2. SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... pnpm badges:upload

-- 1. Create the bucket (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'global-achievement-badges',
  'global-achievement-badges',
  true,
  2097152,  -- 2 MB per PNG (512×512 PNG-24 ~115 KB in practice)
  ARRAY['image/png']
)
ON CONFLICT (id) DO UPDATE
  SET public             = true,
      file_size_limit    = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

-- 2. RLS policies (idempotent)
DROP POLICY IF EXISTS "achievement_badges_public_read"    ON storage.objects;
DROP POLICY IF EXISTS "achievement_badges_service_upload" ON storage.objects;
DROP POLICY IF EXISTS "achievement_badges_service_update" ON storage.objects;
DROP POLICY IF EXISTS "achievement_badges_service_delete" ON storage.objects;

-- Anyone (including anon) can read badge images
CREATE POLICY "achievement_badges_public_read" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'global-achievement-badges');

-- Only service role can write (badges are generated by script, not by end users)
CREATE POLICY "achievement_badges_service_upload" ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'global-achievement-badges'
    AND auth.role() = 'service_role'
  );

CREATE POLICY "achievement_badges_service_update" ON storage.objects
  FOR UPDATE
  USING (
    bucket_id = 'global-achievement-badges'
    AND auth.role() = 'service_role'
  )
  WITH CHECK (
    bucket_id = 'global-achievement-badges'
    AND auth.role() = 'service_role'
  );

CREATE POLICY "achievement_badges_service_delete" ON storage.objects
  FOR DELETE
  USING (
    bucket_id = 'global-achievement-badges'
    AND auth.role() = 'service_role'
  );
